sudo: false
language: node_js
node_js:
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"

before_script:
  - npm i yarn -g

script:
  - npm test

after_script:
  - npm install coveralls@2 && cat ./coverage/lcov.info | coveralls
